apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-lb
spec:
  ports:
    - name: web-port
      port: 80    # LB에 접근하기 위한 포트
      targetPort: 80

  selector:
    app: webserver   # hostname-deployment 서비스의 label
  type: LoadBalancer
