apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-nginx-pods-label
spec: # 리소스 생성하기 위한 자세 정보. 컨테이너 하위 항목인 이미지에서 사용할 nginx 도커 이미지를 지정
  containers:
    - name: my-ngingx-container
      image: nginx:latest
      ports:
        - containerPort: 80
