apiVersion: v1
kind: Pod # 리소스의 종류
metadata: # 라벨, 주석, 이름과 같은 부가 정보
  name: my-nginx-pod
spec: # 리소스 생성하기 위한 자세 정보. 컨테이너 하위 항목인 이미지에서 사용할 nginx 도커 이미지를 지정
  containers:
    - name: my-ngingx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP

    - name: ubuntu-sidecar-container  # 사이드카 패턴이 이건가?
      image: alicek106/rr-test:curl
      command: [ "tail" ]         # command, arg는 컨테이너 내부에서 가장 먼저 실행될 프로세스 지정. 도커의 CMD와 동일.
      args: [ "-f", "/dev/null" ] # 파드가 종료되지 않도록 유지하기 위해 무한 루프를 돌도록 설정
