apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: simple-pdb-example
spec:
  maxUnavailable: 1 # 비활성화 될 수 있는 파드의 최대 개수 또는 비율 (%)
  # minAvailable: 2
  selector:
      matchLabels:
        app: webserver  # PDB 대상이 될 파드를 선택하는 라벨 셀렉터
