apiVersion: v1
kind: Pod
metadata:
  name: init-container-usecase
spec:
  initContainers:   # 초기화 컨테이너
    - name: wait-other-service
      image: busybox
      command: ["sh", "-c", "until nslookup myservice; do echo waiting..; sleep; done;"]
  containers:       # 애플리케이션 컨테이너
    - name: nginx
      image: nginx
