apiVersion: v1
kind: Pod
metadata:
  name: init-container-example
spec:
  initContainers:   # 초기화 컨테이너
    - name: my-init-container
      image: busybox
      command: ["sh", "-c", "echo hello world"]
  containers:       # 애플리케이션 컨테이너
    - name: nginx
      image: nginx
