apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe-pod
spec:
  containers:
  - name: livenessprobe-pod
    image: nginx
    livenessProbe:    # Liveness Probe 설정
      httpGet:
        path: /
        port: 80      # pod ip:80 으로 http 요청을 보내서 정상 응답을 받으면 정상으로 판단
#      initialDelaySeconds: 5
#      periodSeconds: 5
#      failureThreshold: 1
#      successThreshold: 1
#      timeoutSeconds: 1
