apiVersion: v1
kind: Pod
metadata:
  name: prestop-hook
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - name: prestop-hook
      image: nginx
      lifecycle:
        preStop:
          exec:
            command: [ "/usr/sbin/nginx", "-s", "quit" ]
