apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - default:    # 자동으로 설정될 기본 Limit 값
        memory: 256Mi
        cpu: 200m
      defaultRequest: # 자동으로 설정될 기본 Request 값
        memory: 128Mi
        cpu: 100m
      max:            # 자원 할당량의 최대값
        memory: 1Gi
        cpu: 1000m
      min:            # 자원 할당량의 최소값
        memory: 16Mi
        cpu: 50m
      type: Container # 각 컨테이너에 대해서 적용
