apiVersion: v1
kind: Pod
metadata:
  name: memory-over-pod2
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          cpu: "200m"
          memory: "3000Mi"
        requests:
          cpu: "200m"
          memory: "128Mi"
