apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-example
  namespace: default
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "500Mi"
    limits.cpu: "1500m"
    limits.memory: "1000Mi"
    count/pods: "3"
    count/services: "5"
#    count/secrets: "10"
#    count/configmaps: "10"
#    count/persistentvolumeclaims: "5"
#    count/services.nodeports: "5"
#    count/services.loadbalancers: "5"
#    count/deployments.apps: "5"
