apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parent-clusterrole
  labels:
    rbac.authorization.k8s.io/aggregate-to-child-clusterrole: "true"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: child-clusterrole
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:  # 명시된 라벨과 일치하는 라벨을 가진 ClusterRole을 찾아 권한을 그대로 부여받는다.
        rbac.authorization.k8s.io/aggregate-to-child-clusterrole: "true"
rules: [] # 어떠한 권한도 정의하지 않음

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-reader-test

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: parent-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: node-reader-test
    namespace: default
roleRef:
  kind: ClusterRole
  name: child-clusterrole
  apiGroup: rbac.authorization.k8s.io
