apiVersion: v1
kind: ServiceAccount
metadata:
  name: taesu

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-reader
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: taesu
    namespace: default
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-python-sdk
spec:
  serviceAccountName: taesu
  containers:
    - name: k8s-python-sdk
      image: alicek106/k8s-sdk-python:latest
