apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-reader
rules:
  - apiGroups: [""]         # 대상 오브젝트의 API 그룹
    resources: ["services"] # 대상 오브젝트의 이름
    verbs: ["get", "list"]  # 어떠한 동작을 허용할 것인가
