apiVersion: v1
kind: Pod
metadata:
  name: selective-secret-env-example
spec:
  containers:
    - name: my-container
      image: busybox
      args: [ "tail", "-f", "/dev/null" ]
      env:
        - name: YOUR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pw2
              name: our-password

