apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc  # PVC의 이름
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce # 2.1 속성이 ReadWriteOnce인 pv와 연결한다
  resources:
    requests:
      storage: 5Gi # 2.2 볼륨 크기가 최소 5GI인 pv와 연결한다

---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-mount-container
spec:
  containers:
    - name: ebs-mount-container
      image: busybox
      args: [ "tail", "-f", "/dev/null" ]
      volumeMounts:
        - name: ebs-volume
          mountPath: /mnt
  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: my-ebs-pvc # 3. pvc 이름을 지정한다
