apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 5Gi    # EBS 볼륨의 크기
  accessModes:
    - ReadWriteOnce # 볼륨에 대한 접근 권한, 하나의 파드 혹은 인스턴스에 의해서만 마운트 될 수 있다
  awsElasticBlockStore:
    volumeID: vol-0c7e3b2b2b2b2b2b2
    fsType: ext4
  persistentVolumeReclaimPolicy: Delete
